name: CI-CD WorkFlow

on:
    push:
        branches:
            - main

jobs:
    test-job:
        runs-on: ubuntu-latest

        steps:
            - name: checkout code
              uses: actions/checkout@v2

            - name: setup python
              uses: actions/setup-python@v6
              with:
                python-version: '3.10'
            
            - name: install Dependancy
              run: pip install -r requirements.txt
# under this if cov-fail-under = 95 then the deployment is not done           
            - name: Run Test Cases
              run: pytest --cov=calc --cov-report=term --cov-fail-under=80
            
            - name: download code cov
              uses: actions/upload-artifact@v4
              with:
                name: html-cod-cov
                path: htmlcov/
    deploy-job:
        runs-on: ubuntu-latest
        needs: test-job

        steps:
            - name: Print Message
              run: echo "Deployment Started ..."
